### ISSUE TITLE
broadcast初始化报错

### ISSUE THREAD

**Issue by karakoo** [GraiaProject/BroadcastControl#15]
**环境**
`python==3.9.2`
`graia-broadcast==0.11.2`

**运行的代码（示例代码）:**
```Python
import asyncio

from graia.application import (
    GraiaMiraiApplication,
    Session,
)
from graia.broadcast import Broadcast


def main():
    loop = asyncio.get_event_loop()

    bcc = Broadcast(loop=loop)
    app = GraiaMiraiApplication(
        broadcast=bcc,
        connect_info=Session(host='http://localhost:8080')
    )


if __name__ == '__main__':
    main()
```

**报错**
```
Traceback (most recent call last):
  File "Y:\Project\GraiaSource\test\broadcast.py", line 21, in <module>
    main()
  File "Y:\Project\GraiaSource\test\broadcast.py", line 14, in main
    app = GraiaMiraiApplication(
  File "Y:\Project\GraiaSource\graia\application\__init__.py", line 200, in __init__
    self.broadcast.dispatcher_interface.inject_global_raw(
  File "Y:\Project\GraiaSource\graia\broadcast\interfaces\dispatcher.py", line 110, in inject_global_raw
    self.flush_lifecycle_refs(dispatchers)
  File "Y:\Project\GraiaSource\graia\broadcast\interfaces\dispatcher.py", line 84, in flush_lifecycle_refs
    self.get_lifecycle_refs(dispatcher, lifecycle_refs)
```

**Comment by GreyElaina** [comment]
没发全。

**Comment by GreyElaina** [comment]
你 pr 修错地方了。

**Comment by karakoo** [comment]
> 你 pr 修错地方了。

我两个bug加一起修了
